version: '3.8'

services:

  postgres_exporter:
    image: quay.io/prometheuscommunity/postgres-exporter
    container_name: postgres_exporter
    restart: always
    environment:
      DATA_SOURCE_NAME: "postgresql://reader:${READER_PASSWORD}@${POSTGRES_DB}:5432/${POSTGRES_DB}?sslmode=disable"
  
  node_exporter:
    image: prom/node-exporter
    container_name: node_exporter
    restart: always
    pid: host
    network_mode: host
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--web.listen-address=127.0.0.1:9100'

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: always
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    environment:
      - GF_USER=${GF_USER}
      - GF_PASSWORD=${GF_PASSWORD}
    env_file:
      - /root/projects/whaleslayer/.env
    volumes:
      - ./grafana-data:/var/lib/grafana

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
    - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
    - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    env_file:
    - /root/projects/whaleslayer/.env
    volumes:
    - ./pgadmin_data:/var/lib/pgadmin
