pipeline {
  agent { label 'linux-docker-agent' }

  parameters {
    choice(name: 'HOSTS', choices: ['JAPAN_61', 'HONGKONG_93', 'SINGAPUR_49'], description: 'Выбор серверов для деплоя')
    choice(name: 'BRANCHES', choices: ['database', 'monitor'], description: 'Выбор веток проекта для деплоя')
  }

  tools {
    git 'git-linux'
  }

  stages {
    stage('Deploy monitor to Selected Hosts') {
      steps {
        script {
          def sshMap = [
            'JAPAN_61': 'JAP61_ARCH',
            'HONGKONG_93': 'HK93_ARCH',
            'SINGAPUR_49': 'SN49_ARCH'
          ]

          for (host in params.HOSTS.tokenize(',').collect { it.trim() }) {
            def ip = ''
            withCredentials([string(credentialsId: "HOST_${host}", variable: 'HOST_IP')]) {
              ip = HOST_IP
            }

            def cred = sshMap[host]

            sshagent([cred]) {
              sh """
                echo "[*] Установка и проверка Docker и Compose"
                ssh -o StrictHostKeyChecking=no root@${ip} '
                  command -v docker >/dev/null 2>&1 || curl -fsSL https://get.docker.com | sh
                  if ! docker compose version >/dev/null 2>&1; then
                  mkdir -p /usr/libexec/docker/cli-plugins
                  curl -SL https://github.com/docker/compose/releases/latest/download/docker-compose-linux-x86_64 \
                  -o /usr/libexec/docker/cli-plugins/docker-compose
                  chmod +x /usr/libexec/docker/cli-plugins/docker-compose
                  fi
                '

                echo "[*] Подготовка директории проекта"
                ssh root@${ip} 'mkdir -p ~/projects/whaleslayer/monitor'

                echo "[*] Копирование данных ветки с БД"
                scp -r monitor/. root@${ip}:~/projects/whaleslayer/monitor

                echo "[*] Назначение прав для volumes Grafana и pgAdmin"
                ssh root@${ip} '
                  mkdir -p ~/projects/whaleslayer/monitor/grafana_data
                  mkdir -p ~/projects/whaleslayer/monitor/pgadmin_data
                  chown -R 472:472 ~/projects/whaleslayer/monitor/grafana-data || true
                  chown -R 5050:5050 ~/projects/whaleslayer/monitor/pgadmin_data || true
                '

                echo "[*] Проверка и создание сети whaleslayer_local"
                ssh root@${ip} '
                  docker network inspect whaleslayer_local >/dev/null 2>&1 || docker network create whaleslayer_local
                '
                
                echo "[*] Запуск мониторинга с использованием docker compose"
                ssh root@${ip} '
                    cd ~/projects/whaleslayer/monitor &&
                    set -ae &&
                    source /root/projects/whaleslayer/.env &&
                    set +a &&
                    docker compose pull &&
                    docker compose up -d --remove-orphans
                '

                echo "[*] Очистка директории от установочных файлов"
                ssh root@${ip} '
                  cd ~/projects/whaleslayer/monitor/ &&
                  rm -rf Jenkinsfile .gitignore
                '
              """
            }
          }
        }
      }
    }
  }
}